services:
  database:
    image: mariadb:11.7.2
    container_name: work_time_system_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: work_time_system_api_db
      MYSQL_USER: mateusz
      MYSQL_PASSWORD: mateusz
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  database_data:
